### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by scopatz** [ergs/transmutagen-paper#1]
When I run `make` with the latest version of transmutagen installed, I see,

```bash
scopatz@artemis ~/transmutagen-paper master $ make
python -m transmutagen.analysis --origen --no-title --origen-results /home/scopatz/Google\ Drive//ERGS\ Private/transmutagen\ data//scopatz_laptop_results_20170508.hdf5 --file origen-scopatz.pgf
Traceback (most recent call last):
  File "/home/scopatz/miniconda3/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/scopatz/miniconda3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/scopatz/.local/lib/python3.5/site-packages/transmutagen-1.1.0+79.g08719d3-py3.5.egg/transmutagen/analysis.py", line 19, in <module>
    from .tests.test_transmute import run_transmute_test
ImportError: No module named 'transmutagen.tests'
make: *** [Makefile:21: origen-scopatz.pgf] Error 1
```

**Comment by scopatz** [comment]
CC @asmeurer

**Comment by asmeurer** [comment]
OK, some stuff isn't being installed by setup.py. Let me fix it.

**Comment by asmeurer** [comment]
See if it works now (after updating transmutagen).

**Comment by scopatz** [comment]
Yes! Thanks @asmeurer - it seems to have gotten beyond that problem.

**Comment by asmeurer** [comment]
Great. The full build from scratch takes a while unfortunately (like 30 min or something). The good news is the figures are cached, so subsequent builds will be fast unless you do a full clean. Let me know if you have other issues.

**Comment by scopatz** [comment]
Will do!
