### ISSUE TITLE
Cannot find pwru50_400000000000000

### ISSUE THREAD

**Issue by scopatz** [ergs/transmutagen-paper#2]
When I try to run make, I see the following error:

```console
scopatz@artemis ~/transmutagen-paper master $ env TRANSMUTAGEN_DATA=~/transmutagen-data TRANSMUTAGEN=~/transmutagen/transmutagen make
python -m transmutagen.analysis --eigenvals --no-title --file eigenvals.pdf --pwru50-data=/home/scopatz/transmutagen/transmutagen/data/pwru50_400000000000000.0.npz
Traceback (most recent call last):
  File "/home/scopatz/miniconda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/scopatz/miniconda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/scopatz/.local/lib/python3.6/site-packages/transmutagen-1.1.0+80.g25d24cd-py3.6.egg/transmutagen/analysis.py", line 1128, in <module>
    analyze()
  File "/home/scopatz/.local/lib/python3.6/site-packages/transmutagen-1.1.0+80.g25d24cd-py3.6.egg/transmutagen/analysis.py", line 1114, in analyze
    file=args.file, title=args.title)
  File "/home/scopatz/.local/lib/python3.6/site-packages/transmutagen-1.1.0+80.g25d24cd-py3.6.egg/transmutagen/analysis.py", line 396, in analyze_eigenvals
    nucs, matpwru50 = load_sparse_csr(pwru50_data)
  File "/home/scopatz/.local/lib/python3.6/site-packages/transmutagen-1.1.0+80.g25d24cd-py3.6.egg/transmutagen/util.py", line 268, in load_sparse_csr
    loader = np.load(filename)
  File "/home/scopatz/miniconda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 372, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/scopatz/transmutagen/transmutagen/data/pwru50_400000000000000.0.npz'
make: *** [Makefile:25: eigenvals_pwru50.pdf] Error 1
```

This is because the TRANSMUTAGEN variable in the Makefile seems like it should be pointing to the transmutagen dir, rather than the tranmutagen package.  This is pretty confusing and it would be great if it could be made more clear.

**Comment by asmeurer** [comment]
Yes, it should point to the directory containing the package. It is what gets put on PYTHONPATH.

**Comment by scopatz** [comment]
Sorry if this was confusing. It actually has to point to `transmutagen/transmutagen/tests`, not `transmutagen/transmutagen/` right now. It seems like it should point to `transmutagen/transmutagen/`

**Comment by asmeurer** [comment]
Oh, I probably have a bug in transmutagen (I have `transmutagen/tests/data` as well as `data` at the root of the git, with the second being untracked). Let me check it out.

**Comment by scopatz** [comment]
Cool, thanks!

**Comment by asmeurer** [comment]
Ah, it's actually a bug in the Makefile. It used to require that data directory, until I checked it in. If you pull this should work.
